echo "Welcome to Gabriel's Custom Arch ISO!"
echo ""
echo "You can start an i3 graphical display just by executing \"startx\"."
echo "\"Meta + D\" to open menu (to execute \"gparted\")."
echo "\"Meta + Enter\" to execute a terminal session."
echo "\"Meta + Shift + Q\" to close a window."
echo ""
echo "********************************************************"
echo "*                                                      *"
echo "*  Remember to:                                        *"
echo "*  - Mount your partitions.                            *"
echo "*  - Execute \"install.sh\" to install your packages.    *"
echo "*                                                      *"
echo "********************************************************"

