echo "Welcome to Gabriel's Custom Arch ISO!"
echo ""
echo "You can start an Openbox display just by executing \"startx\"."
echo "\"Super + D\" to open menu (to execute \"gparted\")."
echo "\"Super + Enter\" to execute a terminal session."
echo "In a graphical terminal, for a latin-american keyboard execute \"setxkbmap latam\"."
echo ""
echo "Remember to:"
echo "- Mount your partitions"
echo "- Set up your environment in \"env.sh\""
echo "- Execute \"install.sh\" to install your packages"
echo ""

