echo "********************************************************************"
echo "*                                                                  *"
echo "*   Welcome to Gabriel's Custom Arch ISO!                          *"
echo "*                                                                  *"
echo "*   Useful commands:                                               *"
echo "*   (Note: Replace /dev/sdaX with your disk/partition)             *"
echo "*                                                                  *"
echo "*   - Check your disk partitions : lsblk                           *"
echo "*   - Edit your disk partitions  : cfdisk /dev/sda                 *"
echo "*   - Recreate disk from scratch : cfdisk -z /dev/sda              *"
echo "*   - Make a file system         : mkfs.ext4 /dev/sdaX -L 'Arch'   *"
echo "*   - Mount your partitions      : mount /dev/sdaX /mnt            *"
echo "*   - Edit installation settings : vim ./ArchScripts/env.sh        *"
echo "*   - Install Arch Linux         : ./install.sh                    *"
echo "*                                                                  *"
echo "*   Optional commands:                                             *"
echo "*                                                                  *"
echo "*   - Get information of your PC : lspci                           *"
echo "*   - Start a graphical display  : startx                          *"
echo "*   - Startx with bigger fonts   : startx -- -dpi 192              *"
echo "*   - Test your GPU performance  : glxgears                        *"
echo "*   - Run a GUI partition editor : gparted                         *"
echo "*                                                                  *"
echo "********************************************************************"

