USERNAME="gabriel"              # Your username
PASSWORD="arch"                 # Your password (placeholder, the script will prompt for this again)
HOSTNAME="linux-pc"             # The hostname of this particular system
LANGUAGE="es_CL"                # Check /etc/locale.gen for more options
KEYMAP="la-latin1"              # Check /usr/share/kbd/keymaps/**/*.map.gz for more options
ZONEINFO="America/Santiago"     # Check /usr/share/zoneinfo/ for more options
DESKTOP_ENV="KDE"               # KDE, GNOME, i3, X11
BOOTLOADER="refind"             # refind, grub
XORG_DRIVERS="nvidia"           # nvidia, amd, vbox, intel
